title: Next thing next
email: DORNANDLUCAS@gmail.com
description: >-
  The Dorn and Lucas family archive, photo journals, and notes.
baseurl: "/dornlucas"
url: "https://cdorn4.github.io"
lang: en-US
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
future: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - node_modules
  - .jekyll-cache
  - .sass-cache
